# fly.toml app configuration file generated for crypto-exchange-server on 2023-06-27T17:05:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crypto-exchange-server"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
